name: NativeScript Build Android w/ Latest

on: [push]

jobs:
  build-latest:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install Dependencies
      run: |
        npm i
        npm install @angular/cli
    - name: Update & Upgrade
      run: |
        npm i nativescript@latest
        npm i tns-core-modules@latest
        .\tns update
        .\tns plugin update
        .\tns platform add android
        ./node_modules/.bin/update-ns-webpack --deps --configs
        npm rebuild node-sass
    - name: TNS Infos
      run: .\tns info
    - name: Build Android
      run: .\tns build Android
