name: TSLint

on: [push]

jobs:
  tslint:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: npm Install
      run: |
        npm i
    - name: tslint
      run: npm run lint
